"use client"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './index.css'
import Providers from '../redux/provider'
import global_en from "./translations/en/global.json"
import global_ar from "./translations/ar/global.json"
import i18next from 'i18next'
import { I18nextProvider } from 'react-i18next'

const inter = Inter({ subsets: ['latin'] })
i18next.init({
  interpolation: { escapeValue: false },
  lng: "en",
  resources: {
    en: { global: global_en },
    ar: { global: global_ar }
  }
})
// export const metadata: Metadata = {
//   title: 'Touch Tech',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Touch Tech</title>
        <link rel="icon" href="/favicon.ico" />
        <link rel="short icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <I18nextProvider i18n={i18next}>
          <Providers>
            {children}
          </Providers>
        </I18nextProvider>
      </body>
    </html>
  )
}
